### ISSUE TITLE
Default setting for GDNativeLibrary in Project Settings doesn't exist anymore?

### ISSUE THREAD

**Issue by lstep** [ShadowApex/godot-go#27]
Hello,
In **3.0 alpha2**, I can't find anymore the project setting `dlscript/default_dllibrary`. There is now a tab "`GDNative`", but there is no button associated with it. How can I now put a default library?

Thanks for your work.

**Comment by ShadowApex** [comment]
Hi @lstep ,

This is more of a Godot editor issue than a godot-go issue. I'm not sure how they've changed that option. In my testing, I usually create a `libgodot.tres` file which points to the `.so` object that is built.

**Comment by lstep** [comment]
Yes that's what I also did, and you are totally right, that is a Godot issue, but when someone follows your instructions (in the README.md file) he get stuck because of this and can get frustrated. There are so few places where GDNative is documented that it's exceptionally complex (IMHO) to find how to correct this.
