### ISSUE TITLE
Implement all Godot Variant types in Go.

### ISSUE THREAD

**Issue by ShadowApex** [ShadowApex/godot-go#5]
Currently we support basic Godot variant type like `godot_string`, `godot_int`, etc. We need to finish implementing the other types as their own Go structures that wrap around the underlying variant.

**Comment by pastaq** [comment]
Working on Vector2/Vector3.

**Comment by pastaq** [comment]
Vector 2: https://github.com/ShadowApex/godot-go/pull/14

**Comment by pastaq** [comment]
Vector3: https://github.com/ShadowApex/godot-go/pull/15

**Comment by ShadowApex** [comment]
@pastaq 
I noticed some errors after pulling in your code. Here's the problems I see a lot:

```go
func (v *Vector2) Abs() Vector2 {
	var newVec2 Vector2
	newVec2.vector2 = C.godot_vector2_abs(v.vector2)

	return newVec2
}
```

The `C.godot_vector2_abs()` function returns a `C.godot_vector2` object, not a `*C.godot_vector2`. It should instead be implemented like this:

```go
func (v *Vector2) Abs() Vector2 {
	var newVec2 C.godot_vector2
	newVec2 = C.godot_vector2_abs(v.vector2)

	return &Vector2{vector: &newVec2}
}
```

**Comment by pastaq** [comment]
Fixed https://github.com/ShadowApex/godot-go/pull/16

**Comment by pastaq** [comment]
Quat: https://github.com/ShadowApex/godot-go/pull/17

**Comment by pastaq** [comment]
https://github.com/ShadowApex/godot-go/pull/20

**Comment by pastaq** [comment]
Rect2, Rect3, RID update: https://github.com/ShadowApex/godot-go/pull/21

**Comment by pastaq** [comment]
Color: https://github.com/ShadowApex/godot-go/pull/22
